# SPDX-FileCopyrightText: 2024 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause

version = 1

[[annotations]]
path = [
     "printf-emb.c",
     "printf-emb.h",
     "README.md",
]
SPDX-FileCopyrightText = "2018 ee-quipment.com"
SPDX-License-Identifier = "MIT"


