// SPDX-FileCopyrightText: 2026 Tillitis AB <tillitis.se>
// SPDX-License-Identifier: Apache-2.0 OR MIT

#include <stdint.h>
#include <string.h>

#include "ctap_errors.h"

const char *ctap_error_string(CtapStatus error)
{
	switch (error.value) {
	// case CTAP1_ERR_SUCCESS:
	//     return "CTAP1_ERR_SUCCESS";
	case CTAP2_OK:
		return "CTAP2_OK";
	case CTAP1_ERR_INVALID_COMMAND:
		return "CTAP1_ERR_INVALID_COMMAND";
	case CTAP1_ERR_INVALID_PARAMETER:
		return "CTAP1_ERR_INVALID_PARAMETER";
	case CTAP1_ERR_INVALID_LENGTH:
		return "CTAP1_ERR_INVALID_LENGTH";
	case CTAP1_ERR_INVALID_SEQ:
		return "CTAP1_ERR_INVALID_SEQ";
	case CTAP1_ERR_TIMEOUT:
		return "CTAP1_ERR_TIMEOUT";
	case CTAP1_ERR_CHANNEL_BUSY:
		return "CTAP1_ERR_CHANNEL_BUSY";
	case CTAP1_ERR_LOCK_REQUIRED:
		return "CTAP1_ERR_LOCK_REQUIRED";
	case CTAP1_ERR_INVALID_CHANNEL:
		return "CTAP1_ERR_INVALID_CHANNEL";
	case CTAP2_ERR_CBOR_UNEXPECTED_TYPE:
		return "CTAP2_ERR_CBOR_UNEXPECTED_TYPE";
	case CTAP2_ERR_INVALID_CBOR:
		return "CTAP2_ERR_INVALID_CBOR";
	case CTAP2_ERR_MISSING_PARAMETER:
		return "CTAP2_ERR_MISSING_PARAMETER";
	case CTAP2_ERR_LIMIT_EXCEEDED:
		return "CTAP2_ERR_LIMIT_EXCEEDED";
	case CTAP2_ERR_FP_DATABASE_FULL:
		return "CTAP2_ERR_FP_DATABASE_FULL";
	case CTAP2_ERR_LARGE_BLOB_STORAGE_FULL:
		return "CTAP2_ERR_LARGE_BLOB_STORAGE_FULL";
	case CTAP2_ERR_CREDENTIAL_EXCLUDED:
		return "CTAP2_ERR_CREDENTIAL_EXCLUDED";
	case CTAP2_ERR_PROCESSING:
		return "CTAP2_ERR_PROCESSING";
	case CTAP2_ERR_INVALID_CREDENTIAL:
		return "CTAP2_ERR_INVALID_CREDENTIAL";
	case CTAP2_ERR_USER_ACTION_PENDING:
		return "CTAP2_ERR_USER_ACTION_PENDING";
	case CTAP2_ERR_OPERATION_PENDING:
		return "CTAP2_ERR_OPERATION_PENDING";
	case CTAP2_ERR_NO_OPERATIONS:
		return "CTAP2_ERR_NO_OPERATIONS";
	case CTAP2_ERR_UNSUPPORTED_ALGORITHM:
		return "CTAP2_ERR_UNSUPPORTED_ALGORITHM";
	case CTAP2_ERR_OPERATION_DENIED:
		return "CTAP2_ERR_OPERATION_DENIED";
	case CTAP2_ERR_KEY_STORE_FULL:
		return "CTAP2_ERR_KEY_STORE_FULL";
	case CTAP2_ERR_UNSUPPORTED_OPTION:
		return "CTAP2_ERR_UNSUPPORTED_OPTION";
	case CTAP2_ERR_INVALID_OPTION:
		return "CTAP2_ERR_INVALID_OPTION";
	case CTAP2_ERR_KEEPALIVE_CANCEL:
		return "CTAP2_ERR_KEEPALIVE_CANCEL";
	case CTAP2_ERR_NO_CREDENTIALS:
		return "CTAP2_ERR_NO_CREDENTIALS";
	case CTAP2_ERR_USER_ACTION_TIMEOUT:
		return "CTAP2_ERR_USER_ACTION_TIMEOUT";
	case CTAP2_ERR_NOT_ALLOWED:
		return "CTAP2_ERR_NOT_ALLOWED";
	case CTAP2_ERR_PIN_INVALID:
		return "CTAP2_ERR_PIN_INVALID";
	case CTAP2_ERR_PIN_BLOCKED:
		return "CTAP2_ERR_PIN_BLOCKED";
	case CTAP2_ERR_PIN_AUTH_INVALID:
		return "CTAP2_ERR_PIN_AUTH_INVALID";
	case CTAP2_ERR_PIN_AUTH_BLOCKED:
		return "CTAP2_ERR_PIN_AUTH_BLOCKED";
	case CTAP2_ERR_PIN_NOT_SET:
		return "CTAP2_ERR_PIN_NOT_SET";
	case CTAP2_ERR_PUAT_REQUIRED:
		return "CTAP2_ERR_PUAT_REQUIRED";
	case CTAP2_ERR_PIN_POLICY_VIOLATION:
		return "CTAP2_ERR_PIN_POLICY_VIOLATION";
	case CTAP2_ERR_REQUEST_TOO_LARGE:
		return "CTAP2_ERR_REQUEST_TOO_LARGE";
	case CTAP2_ERR_ACTION_TIMEOUT:
		return "CTAP2_ERR_ACTION_TIMEOUT";
	case CTAP2_ERR_UP_REQUIRED:
		return "CTAP2_ERR_UP_REQUIRED";
	case CTAP2_ERR_UV_BLOCKED:
		return "CTAP2_ERR_UV_BLOCKED";
	case CTAP2_ERR_INTEGRITY_FAILURE:
		return "CTAP2_ERR_INTEGRITY_FAILURE";
	case CTAP2_ERR_INVALID_SUBCOMMAND:
		return "CTAP2_ERR_INVALID_SUBCOMMAND";
	case CTAP2_ERR_UV_INVALID:
		return "CTAP2_ERR_UV_INVALID";
	case CTAP2_ERR_UNAUTHORIZED_PERMISSION:
		return "CTAP2_ERR_UNAUTHORIZED_PERMISSION";
	case CTAP1_ERR_OTHER:
		return "CTAP1_ERR_OTHER";
	case CTAP2_ERR_SPEC_LAST:
		return "CTAP2_ERR_SPEC_LAST";
	case CTAP2_ERR_EXTENSION_FIRST:
		return "CTAP2_ERR_EXTENSION_FIRST";
	case CTAP2_ERR_EXTENSION_LAST:
		return "CTAP2_ERR_EXTENSION_LAST";
	case CTAP2_ERR_VENDOR_FIRST:
		return "CTAP2_ERR_VENDOR_FIRST";
	case CTAP2_ERR_USER_PRESENCE_DISABLED:
		return "CTAP2_ERR_USER_PRESENCE_DISABLED";
	case CTAP2_ERR_VENDOR_LAST:
		return "CTAP2_ERR_VENDOR_LAST";
	default:
		return "unknown error";
	}
}
