
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:5rc1
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: Build tkey_app
        run: ./build-tkey.sh

      - name: Build solokeys_linux
        run: make solokeys_linux

  check-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:5rc1
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: check fmt of c code
        run: make checkfmt

